# Site settings
title: kitofr.github.io
email: kitofr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will (hopefully) be a colleciton of my ideas and reflections
  about topics like politics, programming, change, health
baseurl: "." # the subpath of your site, e.g. /blog/
url: "http://kitofr.github.io" # the base hostname & protocol for your site
twitter_username: kitofr
github_username:  kitofr

# Build settings
markdown: kramdown
